# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
