# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 20:15
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0002_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slugfield', editable=False, max_length=255, populate_from=b'titulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(blank=True, default='uuid', editable=False),
            preserve_default=False,
        ),
    ]
