# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 02:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0005_auto_20161016_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
