# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmo.Inmueble')),
                ('respondio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
