# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='geom',
            new_name='location',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ciudad',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
