# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 20:37
from __future__ import unicode_literals

import autoslug.fields
import django.contrib.gis.db.models.fields
from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0003_auto_20161016_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='barrio',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(blank=True, default='uuid', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciudad',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(blank=True, default='uuid', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pais',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='uuid', editable=False, max_length=255, populate_from=b'name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(blank=True, default='uuid', editable=False),
            preserve_default=False,
        ),
    ]
