# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 02:41
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0008_auto_20161016_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, max_length=255, populate_from=b'nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciudad',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, max_length=255, populate_from=b'nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pais',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from=b'nombre'),
        ),
    ]
