# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0010_auto_20161016_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='altura',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ambientes',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='antiguedad',
            field=models.CharField(default=10, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='calle',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cochera',
            field=models.CharField(default='Si', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='patio',
            field=models.CharField(default='Si', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='pileta',
            field=models.CharField(default='No', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='plantas',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio',
            field=models.CharField(default=50000, max_length=10),
            preserve_default=False,
        ),
    ]
